apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lti-env-dev
  namespace: dev-lti
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: lti-env-dev
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: example/lti/dev/env