fullnameOverride: dev-mas-presensi
replicaCount: 1
image:
  repository: 123456789012.dkr.ecr.ap-southeast-3.amazonaws.com/example/mas-presensi
  tag: dev-fc9b56fc
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
envFromSecret: presensi-env-dev
nginx:
  enabled: false
app:
  port: 3000
migrate:
  enabled: true
service:
  port: 80
  targetPort: 3000
ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-southeast-3:123456789012:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    # gunakan root agar tidak bergantung endpoint API internal yang bisa berubah
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/success-codes: "200"
  hosts:
    - host: dev-mas-presensi.example.com
      paths:
        - path: /
          pathType: Prefix
