{{- if .Values.migrate.enabled -}}
{{- $tag := default .Chart.AppVersion .Values.image.tag -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mas-presensi.fullname" . }}-migrate-{{ $tag | replace "." "-" | replace "_" "-" | lower }}
  labels:
    {{- include "mas-presensi.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/hook-delete-policy": BeforeHookCreation,HookSucceeded,HookFailed
    "argocd.argoproj.io/sync-wave": "-1"
spec:
  backoffLimit: {{ .Values.migrate.backoffLimit | default 2 }}
  template:
    metadata:
      labels:
        {{- include "mas-presensi.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          command: ["sh","-lc"]
          args:
            - {{ .Values.migrate.command | quote }}
          {{- if .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret | quote }}
          {{- end }}
{{- end -}}
