apiVersion: v1
kind: Service
metadata:
  name: {{ include "mas-presensi.fullname" . }}
  labels:
    {{- include "mas-presensi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "mas-presensi.selectorLabels" . | nindent 4 }}