apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "redis.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "redis.fullname" . }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6379
          {{- if .Values.auth.enabled }}
          env:
            - name: REDIS_PASSWORD
              value: {{ .Values.auth.password | quote }}
          {{- end }}