apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: presensi-env-dev
  namespace: dev-presensi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: presensi-env-dev
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: mbugroup/mas-presensi/dev/env
             