apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sso-env
  namespace: dev-sso
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: sso-env-dev
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: example/sso/dev/env