replicaCount: 1
image:
  repository: 123456789012.dkr.ecr.ap-southeast-3.amazonaws.com/example/sso-api
  tag: prod-bec7da77
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 7001 # sesuaikan port container SSO kamu
envFromSecret: sso-env-prod
redisAlias:
  enabled: true
keys:
  enabled: true
  secretName: sso-jwt-keys
  mountPath: /app/internal/config/keys
ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip
  host: api-sso.example.com
  listenPorts: '[{"HTTP":80},{"HTTPS":443}]'
  certificateArn: "arn:aws:acm:ap-southeast-3:123456789012:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  sslRedirect: "443"

migrate:
  enabled: false
  backoffLimit: 1
  ttlSecondsAfterFinished: 300
  command: >-
    DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}";
    /app/migrate -path /app/migrations -database "$DATABASE_URL" up
