global:
  image:
    repository: 123456789012.dkr.ecr.ap-southeast-3.amazonaws.com/example/tools
    tag: argocd-v3.3.1-amd64

  nodeSelector:
    kubernetes.io/arch: amd64

# opsional tapi bagus untuk memastikan hook/job juga ikut:
configs:
  cm:
    # boleh kosong, cuma contoh struktur
    application.instanceLabelKey: argocd.argoproj.io/instance

redis:
  image:
    repository: 123456789012.dkr.ecr.ap-southeast-3.amazonaws.com/example/redis
    tag: 7-alpine

dex:
  enabled: false
