replicaCount: 1
image:
  repository: 886436954922.dkr.ecr.ap-southeast-3.amazonaws.com/mbugroup/sso-api
  tag: dev-e60d7c5f
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 7001 # sesuaikan port container SSO kamu
envFromSecret: sso-env-dev
keys:
  enabled: true
  secretName: sso-jwt-keys
  mountPath: /app/internal/config/keys
redisAlias:
  enabled: false
ingress:
  enabled: true
  className: alb
  scheme: internet-facing
  targetType: ip
  host: dev-api-sso.mbugroup.id
  listenPorts: '[{"HTTP":80},{"HTTPS":443}]'
  certificateArn: arn:aws:acm:ap-southeast-3:886436954922:certificate/6549781d-68ce-4f59-9415-d5c71866a311
  sslRedirect: "443"
migrate:
  enabled: true
  backoffLimit: 1
  ttlSecondsAfterFinished: 300
  command: >-
    DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}"; /app/migrate -path /app/migrations -database "$DATABASE_URL" up
