apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-apps
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  source:
    repoURL: https://gitlab.com/cristian.anggita.parjaman/gitops.git
    targetRevision: main
    path: argocd/project/applications
    directory:
      recurse: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true