apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lti-prod
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-lti

  sources:
    - repoURL: https://gitlab.com/cristian.anggita.parjaman/gitops.git
      targetRevision: main
      path: charts/lti
      helm:
        releaseName: prod-lti
        valueFiles:
          - $values/environments/lti/prod/lti-values-prod.yaml

    - repoURL: https://gitlab.com/cristian.anggita.parjaman/gitops.git
      targetRevision: main
      ref: values

    - repoURL: https://gitlab.com/cristian.anggita.parjaman/gitops.git
      targetRevision: main
      path: environments/lti/prod/external-secrets/
      directory:
        recurse: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true