apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lti.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "lti.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "lti.fullname" . }}
    spec:
      containers:
        - name: lti
          image: "{{ required "image.repository is required" .Values.image.repository }}:{{ required "image.tag is required" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}  # ✅ 8081

          {{- if .Values.envFromSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.envFromSecret | quote }}
          {{- end }}

                    {{- if .Values.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}

          {{- if .Values.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}