apiVersion: v1
kind: Service
metadata:
  name: {{ include "lti.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "lti.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}              # 80
      targetPort: {{ .Values.service.targetPort }}  # ✅ 8081